/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\Kabschuur.glb -T 
Files: public\model\Kabschuur.glb [66.7MB] > D:\House\Configrated House\Kabschuur-transformed.glb [3.72MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Kabschuur-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube040.geometry} material={materials['Spruce wood']} position={[0.141, 1.523, -0.051]} scale={[0.999, 0.042, 1.864]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['Dark wood']} position={[0.141, 1.898, -0.013]} scale={[1, 1, 1.594]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Wood Black']} position={[0.123, 1.913, -0.013]} rotation={[0, 0, -0.427]} scale={[0.065, 0.065, 0.064]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.Tiles} position={[0.012, 0.02, 0.026]} scale={2.389} />
    </group>
  )
}

useGLTF.preload('/Kabschuur-transformed.glb')
