/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\Platak.glb -T 
Files: public\model\Platak.glb [62.32MB] > D:\House\Configrated House\Platak-transformed.glb [3.47MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Platak-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube055.geometry} material={materials['Spruce wood']} position={[0, 1.51, 0.017]} scale={[0.999, 0.042, 1.864]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Tiles} position={[0.007, 0.015, 0.064]} scale={[1.845, 2.574, 2.574]} />
      <mesh geometry={nodes.Cube090.geometry} material={materials['Wood Black']} position={[0, 1.51, 0.017]} scale={[0.999, 0.042, 1.864]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Dark wood']} position={[0.032, -0.002, 0.794]} scale={0.846} />
      <mesh geometry={nodes.Cube070.geometry} material={materials['Door Handle']} position={[0.922, 0.58, 0.577]} rotation={[0, Math.PI / 2, 0]} scale={[0.001, 0.055, 0.043]} />
      <group position={[0.922, 0.581, 0.811]} rotation={[0, Math.PI / 2, 0]} scale={0.572}>
        <mesh geometry={nodes.Cube077.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube077_1.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Latch003.geometry} material={materials['Material.001']} position={[0.922, 0.581, 0.811]} rotation={[0, Math.PI / 2, 0]} scale={0.572} />
    </group>
  )
}

useGLTF.preload('/Platak-transformed.glb')
