/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\floor.glb -T 
Files: public\model\floor.glb [18.22MB] > D:\House\Configrated House\floor-transformed.glb [1.33MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Floor(props) {
  const { nodes, materials } = useGLTF('./model/floor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Tiles} position={[0.079, 0.006, 0.041]} scale={[2.552, 3.56, 2.818]} />
    </group>
  )
}

useGLTF.preload('./model/floor-transformed.glb')
