/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\Zadeldak.glb -T 
Files: public\model\Zadeldak.glb [65.82MB] > D:\House\Configrated House\Zadeldak-transformed.glb [3.68MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Zadeldak(props) {
  const { nodes, materials } = useGLTF('./model/Zadeldak-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} material={materials['Spruce wood']} position={[-0.014, 1.898, -0.068]} scale={[1, 1, 1.594]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Wood Black']} position={[-0.032, 1.913, -0.068]} rotation={[0, 0, -0.427]} scale={[0.065, 0.065, 0.064]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Dark wood']} position={[-0.023, 1.366, 1.531]} rotation={[Math.PI / 2, 0, 0]} scale={0.418} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.Tiles} position={[-0.007, -0.023, 0.062]} scale={[1.845, 2.574, 2.574]} />
    </group>
  )
}

useGLTF.preload('./model/Zadeldak-transformed.glb')
